
export default {
  ADD_RANDOM_NUMBER:'ADD_RANDOM_NUMBER',
  REGISTER:'REGISTER',
  LOGIN:'LOGIN',
  LOGOUT:'LOGOUT',
  EDIT_PLAYER:'EDIT_PLAYER',
  LOAD_PLAYERS:'LOAD_PLAYERS'
  // REGISTERED:'REGISTERED'
}
