
export default {
  ADD_RANDOM_NUMBER:'ADD_RANDOM_NUMBER',
  REQUEST_REGISTRATION:'REQUEST_REGISTRATION',
  REGISTERED:'REGISTERED',
  REQUEST_LOGIN:'REQUEST_LOGIN',
  LOGGED_IN:'LOGGED_IN',
  REQUEST_LOGOUT:'REQUEST_LOGOUT',
  LOGGED_OUT:'LOGGED_OUT',
  EDIT_PLAYER:'EDIT_PLAYER',
  LOADED_PLAYERS:'LOADED_PLAYERS',
  ERROR:'ERROR',
  CLEAR_ERROR:'CLEAR_ERROR'
  // REGISTERED:'REGISTERED'
}
